### ISSUE TITLE
todo extra

### ISSUE THREAD

**Issue by Ab2nour** [Ab2nour/stock-analysis#26]
# Todo

- [ ] do a plot like this 

![Image](https://github.com/user-attachments/assets/8752e819-223d-49ee-ae8d-645f254bc0fd)

## Trend

- [x] refactor classes for trend file (use inheritance)
- [ ] General Additive Model (GAM) for trend
- [ ] LOESS (maybe it is for decomposition only?)
- [ ] STL (maybe it is for decomposition only?)

## Prediction

- [x] [Prophet model](https://facebook.github.io/prophet/docs/quick_start.html)
- [ ] [GluonTS for probabilistic prediction](https://github.com/awslabs/gluonts)
- [ ] use [Neural Prophet](https://neuralprophet.com/contents.html) instead of Prophet (both don't work together from what I tested)
- [ ] [Garch](https://github.com/bashtage/arch/)

## Old todo file
- [ ] afficher toutes les variables (on n'a que "Close" actuellement) ?
  - [ ] notamment afficher la variable Volume
  - [ ] afficher des box plots ?
  - [ ] principaux plots à faire pour des time series https://www.geeksforgeeks.org/8-types-of-plots-for-time-series-analysis-using-python/
  - [ ] guide complet https://www.kaggle.com/code/prashant111/complete-guide-on-time-series-analysis-in-python/notebook
  - [ ] seasonal plot à la main ? https://gist.github.com/arthurcgusmao/39905499340d28fa59834f652905dcec
  - [ ] from statsmodels.graphics.tsaplots import month_plot, quarter_plot
  - [ ] from statsmodels.tsa.seasonal import seasonal_decompose
- [ ] afficher seasonal plot polar
- [ ] méthodes de base de traitement d'une série temporelle
  - [ ] enlever la tendance
  - [ ] enlever la saisonnalité
  - [ ] enlever les cycle
- [ ] afficher les rendements ( $X_t / X_{t-1}$ )
- [ ] afficher la volatilité
- [ ] Savitzky Golay => méthode utilisée par Vincent
- [ ] seasonal plot & polar plot => demander à PE (ils ont fait cours action & saisonalité)
- [ ] modèles:
  - [ ] AR
  - [ ] MA
  - [ ] ARMA
  - [ ] ARIMA
